#pragma once

enum class BRLStatus
{
	INVALID = -1,
	SUCCESS = 0,

	FILE_WRITE_WRITEFILE_FAILED,
	FILE_WRITE_WRITEFILE_PARTIAL_WRITE,
	FILE_S_CREATE_FILE_CREATEFILEW_FAILED,

	REGNODE_SUBKEY_VALUE_HAS_NO_SUBKEYS,
	REGNODE_KEY_GET_REGOPENKEYEXW_FAILED,
	REGNODE_KEY_PATH_NTQUERYKEY_FAILED_TO_GET_RESULT_LENGTH,
	REGNODE_KEY_PATH_NTQUERYKEY_FAILED,
	REGNODE_KEY_INFO_REGQUERYINFOKEYW_FAILED_TO_GET_CLASS_NAME_LENGTH,
	REGNODE_KEY_INFO_REGQUERYINFOKEYW_FAILED,
	REGNODE_ITER_INCREMENT_OPERATOR_REGENUMKEYEXW_FAILED,
	REGNODE_ITER_INCREMENT_OPERATOR_REGENUMVALUEW_FAILED,
	REGNODE_ITER_DEREF_OPERATOR_ITERATOR_EXHAUSTED,
};
